# -*- mode: org; eva: (decide-mode); org-d20-party: (("Sarjor" . 7) ("Lindoma" . 0)); -*-
#+title: Sarjor and Lindoma

* Player Characters
- [[file:sarjor.org][Sarjor]]
- [[file:lindoma.org][Lindoma]]

* Themes
- [ ] Avoid Lindoma's enemy
- [x] Explore Goblin Lair @1508
- [ ] Hafling's skull, found in Goblin Lair
- [ ] Village council in Szent Fa

* NPC Characters
- Lindoma's enemy
- King Hugo, king of the region
- Amathahu, evil wizard who woke Betlahya
- Goblin Lair Mage
- Mishka, Szent Fa Chief
- Olah, Szent Fa Shamanka
- Toth, Szent Fa Lieutenant

* Region - Fosgi Coidwig
- Temperate climate
- Human kingdom, lawful, civilized, unsafe, contested

* Background

*Betlahya* is an old, old god largely forgotten. He tried to influence the nature
of the world, but the other gods saw this as corruption. Playing the victim, he
fought against them and lost. He was exiled to a lost and barrn plane almost
completely forgotten in the world of men. A lone mage, *Amathahu*, found reference
to him in a solitary tome. Seeing this as an opportunity to gain further power,
he managed to form a link to Betlahya's prison plane. This was enough for
Betlahya to exert influence again on the material plane. Thus the cult of
Betlahya began as an attempt to return to the "purity" of creation's original
state as Betlahya intended.

The cult has infiltrated many of the settlements. Blood is required to open the
rift between planes. Some cultist are open and some are hidden. People are
fearful and suspicious of what's happening around them.

*King Hugo* is not a strong ruler. His carlessness is what allowed the cult to
perpetrate these attrocities. Sensing his people's mood, the king is now trying
to get the cult under control and diminish its power. His hope is to redeem his
legacy.

* Sessions
** [[file:sessions/2024-07-29.org][Session 1 - <2024-07-29> In which we learn more about our heroes]]
** [[file:sessions/2024-07-30.org][Session 2 - <2024-07-30>]]
Our heroes enter Fosgi Coidwig in search of a settlement. After a day and a
half, they find a Goblin Lair instead.
** [[file:sessions/2024-08-06.org][Session 3 - <2024-08-06>]]
While in the Goblin Lair, the heroes have a nasty encounter with a Bugbear.

This encounter was quite deadly. Sarjor was knocked unconscious twice and twice
failed his death save. Another round would have put him at 50/50 to die. Lindoma
was down to their last breath and wouldn't withstand another blow. Meanwhile,
the Bugbear was down to his last HP and decided to flee! In its panic, he
provoked two opportunity attacks. Lindoma missed the first, but managed to
scratch the Bugbear on the second inflicting a single point of damage. Thus the
Bugbear was slain.
** [[file:sessions/2024-08-12.org][Session 4 - <2024-08-12>]]
The team went back into the Goblin Lair to finish exploring. They found a Goblin
Hexer in the Wizard's chamber along with a Blackblade and two Cutters. After
defeating the Hexer, they found some magic items. Further exploration of the
lair uncovered a halfling's skull with a perfect circular hole in the top as if
part of some dark ritual. Another day's exploration in the wilderness and the
pair came across the village of [[file:szent-fa-1411.org][Szent Fa]] with a great, mystical tree in the
center.
