#+title: Session 1 - <2024-07-29>

* Session 1 - <2024-07-29 Mon>

[[file:lindoma.org][Lindoma]] and [[file:sarjor.org][Sarjor]] are cousins who grew up together. Sarjor's father is
Lindoma's paternal uncle. Lindoma's father was elvish and his mother was human.
Both parents were enslaved during an orc raid. That's why he was raised by
Sarjor's father. Their home was a modest dwelling in the woodland elf enclave.

Sarjor's father was a respected military captain and taught him everything he
knows about surviving and righting in the wild. He became a Scout for their
local militia and became very skilled. He fell in love with a girl from their
community, but she was taken in the same raid as Lindoma's parents. This left
him with a deep hatred of the Orcs and a desire to protect what's good from
them.

There was a warrior in the clan and they had a rift even though Lindoma was
blameless. It became serious. That was what pushed him away from the clan and
start wandering: to stay away from his enemy. He might as well see the world,
learning more songs, and entertaining others along the way.

When Lindoma decided to leave home, due to their close friendship, Sarjor went
with him to watch over him. While out on the road, it's his desire to explore
new forests and learn more about the land and those who inhabit it.
